@ECHO OFF
CALL 00_setVariables.bat
ECHO compiling...
javac ConsortialPartner.java
javac MatrixCreator.java
javac Partner.java
javac Person.java
javac Project.java
javac Workpackage.java
javac ProjectConfigData.java
javac IOProject.java
javac KeyPersonnel.java
javac EffortLevel.java
javac WPSummaryData.java
javac WPSummaryTable.java
javac PartnerSummaryData.java
javac PartnerSummaryTable.java
javac BudgetPerCountry.java
javac Milestone.java
javac MilestoneTable.java
javac Meeting.java
javac MeetingTable.java
javac Task.java
javac TaskTable.java
@ECHO ON